# Generated by Django 4.1 on 2022-08-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('service_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('btn_text', models.CharField(max_length=50)),
            ],
        ),
    ]
