# Generated by Django 4.1 on 2022-08-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contactus_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalInfo',
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Service'},
        ),
    ]
